### ISSUE TITLE
This mod brakes flooded weather.

### ISSUE THREAD

**Issue by YourWaltNightmare** [Fredolx/lc-meteo-multiplier#8]
Whenever I enable this mod, water level on flooded maps never increase. Its always the same.

**Comment by Fredolx** [comment]
Are you running other mods with meteo-multiplier? If so, please list them here

**Comment by YourWaltNightmare** [comment]
Would be easier to send screenshot:
![image](https://github.com/Fredolx/lc-meteo-multiplier/assets/109439715/53e64d78-965f-4613-8e43-a38ecbdeff9b)

**Comment by YourWaltNightmare** [comment]
![image](https://github.com/Fredolx/lc-meteo-multiplier/assets/109439715/1b3ad702-487f-40f5-8b8a-c9cc6bbd3af3)

**Comment by Fredolx** [comment]
Mods like shiplobby or late company can cause synchronisation issues for weather. Can you retest with those mods disabled? Thank you

**Comment by YourWaltNightmare** [comment]
Ok. I'll try to check it.

**Comment by YourWaltNightmare** [comment]
Yeah. I gues the problem was in Shiplobby as I turned back on LGU mod and everything seems fine lately. Atleast for now.
Meanwhile shiplobby last update was 4 month ago, so it seems outated.
Maybe it caused some HUD animations error.

**Comment by Fredolx** [comment]
That's great. Have fun with your mods. I'll close this issue.
